// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtqulphcvsudbgbreqjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0cXVscGhjdnN1ZGJnYnJlcWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTc4OTYsImV4cCI6MjA3NDQ3Mzg5Nn0.DM8D-HVpqIVg3ZCX2cgcPsSt5g3freKTr23nLvpbgjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});